### ISSUE TITLE
Problema ao habilitar módulo

### ISSUE THREAD

**Issue by DiegoGermano** [Ceicom/Ceicom_EbitIntegration#1]
Olá estou tentado dificuldade para instalar o módulo, ele pede o Idbuscapé como obrigatório, porém, já vi que em outras informações não é necessário essa informação e tambem no email com o passo a passo da e-bit não tem essa informação

Preciso realmente do Idbuscapé? e qual sua finalidade

Obrigado

**Comment by jonatanaxe** [comment]
Opa beleza Diego
Nao lembro bem certo mas tinha na documentation tenta colocar qualquer numero 111111

E tambem pode remover do 
 /app/design/frontend/base/default/template/ceicom/ebitintegration/ebitintegration.phtml

**Comment by DiegoGermano** [comment]
Deu certo Jonata, muito obrigado! tinha colocado 00000 e estava retornando um erro, abraço!

**Comment by jonatanaxe** [comment]
Nice
Abraços
